DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS grant_stats;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS grants;
DROP TABLE IF EXISTS services;
